# Site
title:              Mateus Gurgel
bio:                'Developer. Previously, toddler.'
description:        "a blog about magu's side projects and other tech adventures"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/fish-fear-me.jpeg'
# background:         'assets/img/curve-of-city-building-from-below.jpg'
tiled_bg:           false
locale:             en_US
url:                https://magu.dev

# Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   notmagu

# Social
# google:
#   plus:            #username
#   analytics:
#   verify:
#   ad-client:
#   ad-slot:
# bing-verify:
# email:
# twitter:            username
# facebook:           username
github-url:        msgurgel
# stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          msgurgel
# xing:              username
# instagram:          username
# lastfm:            username
# tumblr:            username
# medium:            '@username'
# pinterest:         username
# foursquare:        username
# steam:              username
# dribbble:          username
# youtube:           username
# youtube-channel:   channel
# soundcloud:        username
# weibo:             username
# flickr:            username
# codepen:           username
# keybase:           username
# xmpp:              username@server.com
# hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
